--------------------------------------------------------------------------------
-- addon_game_mode.lua
-- Dota 2 entry point for Enfos Team Survival — SametC Edition
-- This file is loaded by the engine. It delegates to EnfosSametC game mode class.
--------------------------------------------------------------------------------

require("enfos_sametc")
-- The shared Lua ability file owns the callbacks for all custom kits. Load it
-- at addon bootstrap as well as through each KV ScriptFile so missing classes
-- fail visibly before hero selection instead of degrading into empty casts.
require("abilities/pve_kits")

local function assertAbilityCallback(abilityName, callbackName)
	local abilityClass = _G[abilityName]
	if type(abilityClass) ~= "table" or type(abilityClass[callbackName]) ~= "function" then
		error(string.format("Ability Lua callback missing: %s:%s", abilityName, callbackName))
	end
end

assertAbilityCallback("bulwark_shield_slam", "OnSpellStart")
assertAbilityCallback("bulwark_shield_slam", "OnProjectileHit")
assertAbilityCallback("bulwark_challenge", "OnSpellStart")
assertAbilityCallback("bulwark_iron_guard", "GetIntrinsicModifierName")
assertAbilityCallback("modifier_bulwark_iron_guard", "OnAttackLanded")
print("[SVEN_ABILITY_BOOTSTRAP] Q/W/E Lua handlers registered")

local WaveManager = require("waves/wave_manager")

function Precache(context)
    for _, particle in ipairs({
        "particles/ui_mouseactions/range_display.vpcf",
        "particles/items_fx/dust_of_appearance.vpcf",
        "particles/units/heroes/hero_omniknight/omniknight_purification.vpcf",
        "particles/units/heroes/hero_enigma/enigma_demonic_conversion.vpcf",
    }) do PrecacheResource("particle", particle, context) end
    -- Validated replacements for resource names introduced in the hero refresh.
    for _,particle in ipairs({
        "particles/units/heroes/hero_tidehunter/tidehunter_anchor_hero.vpcf",
        "particles/units/heroes/hero_monkey_king/monkey_king_furarmy_aoe.vpcf",
        "particles/units/heroes/heroes_underlord/abyssal_underlord_firestorm_wave.vpcf",
        "particles/units/heroes/heroes_underlord/underlord_pitofmalice.vpcf",
        "particles/units/heroes/heroes_underlord/abbysal_underlord_darkrift_ambient_end.vpcf",
        "particles/items_fx/black_king_bar_avatar.vpcf",
    }) do PrecacheResource("particle",particle,context) end
    PrecacheUnitByNameSync("npc_dota_shadow_shaman_ward_1",context)
	-- Precache custom creature models without synchronously instantiating every
	-- unit definition. PrecacheUnitByNameSync on all 45 custom units and all 40
	-- selectable heroes stalled the game thread during CUSTOM_GAME_SETUP, before
	-- the setup manager could receive team/difficulty/start events.
	local units=LoadKeyValues("scripts/npc/npc_units_custom.txt") or {}
	units=units.DOTAUnits or units
	for name,definition in pairs(units) do
		if type(definition)=="table" and definition.BaseClass then
			if definition.Model then PrecacheResource("model",definition.Model,context) end
			if definition.ProjectileModel then PrecacheResource("particle",definition.ProjectileModel,context) end
		end
	end
	for _,name in ipairs({"sven","juggernaut","drowranger","lina","omniknight"}) do
		PrecacheResource("soundfile","soundevents/game_sounds_heroes/game_sounds_"..name..".vsndevts",context)
	end
	PrecacheResource("particle","particles/units/heroes/hero_sven/sven_warcry_buff.vpcf",context)
	PrecacheResource("particle", "particles/units/heroes/hero_sven/sven_storm_bolt_projectile_trail.vpcf", context)
	PrecacheResource("particle", "particles/units/heroes/hero_sven/sven_storm_bolt_projectile_explosion.vpcf", context)
	PrecacheResource("particle", "particles/units/heroes/hero_sven/sven_spell_great_cleave.vpcf", context)
	PrecacheResource("particle", "particles/units/heroes/hero_sven/sven_spell_great_cleave_gods_strength.vpcf", context)
	PrecacheResource("particle","particles/units/heroes/hero_sven/sven_spell_gods_strength.vpcf",context)
	PrecacheResource("particle","particles/units/heroes/hero_sven/sven_gods_strength_hero_effect.vpcf",context)
	PrecacheResource("particle", "particles/units/heroes/hero_tidehunter/tidehunter_gush.vpcf", context)
	PrecacheResource("particle", "particles/units/heroes/hero_tidehunter/tidehunter_spell_ravage.vpcf", context)
	PrecacheResource("particle", "particles/units/heroes/hero_dragon_knight/dragon_knight_breathe_fire.vpcf", context)
	PrecacheResource("particle", "particles/units/heroes/hero_dragon_knight/dragon_knight_dragon_tail_impact.vpcf", context)
	PrecacheResource("particle", "particles/units/heroes/hero_dragon_knight/dragon_knight_breathe_fire_explosion.vpcf", context)
	PrecacheResource("particle", "particles/units/heroes/hero_dragon_knight/dragon_knight_transform_red.vpcf", context)
	PrecacheResource("particle", "particles/units/heroes/hero_dragon_knight/dragon_knight_elder_dragon_fire_explosion.vpcf", context)
	PrecacheResource("model", "models/heroes/dragon_knight/dragon_knight_dragon.vmdl", context)
	PrecacheResource("particle", "particles/units/heroes/hero_pudge/pudge_meathook.vpcf", context)
	PrecacheResource("particle", "particles/units/heroes/hero_pudge/pudge_meathook_impact.vpcf", context)
	PrecacheResource("particle", "particles/units/heroes/hero_pudge/pudge_rot.vpcf", context)
	PrecacheResource("particle", "particles/units/heroes/hero_pudge/pudge_dismember.vpcf", context)
	PrecacheResource("particle", "particles/units/heroes/hero_ursa/ursa_earthshock.vpcf", context)
	PrecacheResource("particle", "particles/units/heroes/hero_ursa/ursa_overpower_buff.vpcf", context)
	PrecacheResource("particle", "particles/units/heroes/hero_ursa/ursa_enrage_buff.vpcf", context)
	PrecacheResource("particle", "particles/units/heroes/hero_ursa/ursa_fury_swipes.vpcf", context)
	PrecacheResource("particle", "particles/units/heroes/hero_ursa/ursa_fury_swipes_debuff.vpcf", context)
	PrecacheResource("particle", "particles/units/heroes/hero_monkey_king/monkey_king_strike.vpcf", context)
	PrecacheResource("particle", "particles/units/heroes/hero_monkey_king/monkey_king_spring.vpcf", context)
	PrecacheResource("particle", "particles/units/heroes/hero_monkey_king/monkey_king_spring_cast.vpcf", context)
	PrecacheResource("particle", "particles/units/heroes/hero_monkey_king/mk_strike_path_pulse_hit.vpcf", context)
	PrecacheResource("particle", "particles/units/heroes/hero_monkey_king/monkey_king_furarmy_singlemonkey_attack_swipe.vpcf", context)
	PrecacheResource("particle", "particles/units/heroes/hero_monkey_king/monkey_king_fur_army_attack.vpcf", context)
	PrecacheResource("particle", "particles/units/heroes/hero_troll_warlord/troll_warlord_whirling_axe_melee.vpcf", context)
	PrecacheResource("particle", "particles/units/heroes/hero_troll_warlord/troll_warlord_battletrance_buff.vpcf", context)
	PrecacheResource("particle", "particles/units/heroes/hero_troll_warlord/troll_warlord_battletrance_cast.vpcf", context)
	PrecacheResource("particle", "particles/units/heroes/hero_troll_warlord/troll_warlord_rampage_attack_speed_buff.vpcf", context)
	PrecacheResource("particle", "particles/units/heroes/hero_troll_warlord/troll_warlord_rampage_resistance_buff.vpcf", context)
	PrecacheResource("particle", "particles/generic_gameplay/generic_stunned.vpcf", context)
	PrecacheResource("particle", "particles/units/heroes/hero_chaos_knight/chaos_knight_chaos_bolt.vpcf", context)
	PrecacheResource("particle", "particles/units/heroes/hero_chaos_knight/chaos_knight_reality_rift.vpcf", context)
	PrecacheResource("particle", "particles/units/heroes/hero_chaos_knight/chaos_knight_reality_rift_buff.vpcf", context)
	PrecacheResource("particle", "particles/units/heroes/hero_chaos_knight/chaos_knight_phantasm.vpcf", context)
	PrecacheResource("particle", "particles/units/heroes/hero_chaos_knight/chaos_knight_weapon_blur_critical.vpcf", context)
	PrecacheResource("particle", "particles/units/heroes/hero_antimage/antimage_blink_start.vpcf", context)
	PrecacheResource("particle", "particles/units/heroes/hero_antimage/antimage_blink_end.vpcf", context)
	PrecacheResource("particle", "particles/units/heroes/hero_antimage/antimage_manavoid.vpcf", context)
	PrecacheResource("particle", "particles/units/heroes/hero_antimage/antimage_manabreak_enemy_debuff.vpcf", context)
	PrecacheResource("particle", "particles/units/heroes/hero_antimage/antimage_spellshield.vpcf", context)
	PrecacheResource("particle", "particles/units/heroes/hero_faceless_void/faceless_void_time_walk.vpcf", context)
	PrecacheResource("particle", "particles/units/heroes/hero_faceless_void/faceless_void_chronosphere.vpcf", context)
	PrecacheResource("particle", "particles/units/heroes/hero_faceless_void/faceless_void_timedialate.vpcf", context)
	PrecacheResource("particle", "particles/units/heroes/hero_faceless_void/faceless_void_dialatedebuf.vpcf", context)
	PrecacheResource("particle", "particles/units/heroes/hero_faceless_void/faceless_void_time_lock_bash.vpcf", context)
	PrecacheResource("particle", "particles/units/heroes/hero_faceless_void/faceless_void_backtrack.vpcf", context)
	PrecacheResource("particle", "particles/units/heroes/hero_medusa/medusa_mystic_snake_projectile.vpcf", context)
	PrecacheResource("particle", "particles/units/heroes/hero_medusa/medusa_mystic_snake_impact.vpcf", context)
	PrecacheResource("particle", "particles/units/heroes/hero_medusa/medusa_base_attack.vpcf", context)
	PrecacheResource("particle", "particles/units/heroes/hero_medusa/medusa_base_attack_impact.vpcf", context)
	PrecacheResource("particle", "particles/units/heroes/hero_medusa/medusa_stone_gaze_active.vpcf", context)
	PrecacheResource("particle", "particles/units/heroes/hero_medusa/medusa_stone_gaze_debuff.vpcf", context)
	PrecacheResource("particle", "particles/units/heroes/hero_terrorblade/terrorblade_reflection_slow.vpcf", context)
	PrecacheResource("particle", "particles/units/heroes/hero_terrorblade/terrorblade_metamorphosis.vpcf", context)
	PrecacheResource("particle", "particles/units/heroes/hero_terrorblade/terrorblade_mirror_image.vpcf", context)
	PrecacheResource("particle", "particles/units/heroes/hero_terrorblade/terrorblade_metamorphosis_base_attack.vpcf", context)
	PrecacheResource("particle", "particles/units/heroes/hero_terrorblade/terrorblade_sunder.vpcf", context)
	PrecacheResource("particle", "particles/units/heroes/hero_stormspirit/stormspirit_static_remnant.vpcf", context)
	PrecacheResource("particle", "particles/units/heroes/hero_stormspirit/stormspirit_ball_lightning.vpcf", context)
	PrecacheResource("particle", "particles/units/heroes/hero_stormspirit/stormspirit_electric_vortex.vpcf", context)
	PrecacheResource("particle", "particles/units/heroes/hero_stormspirit/stormspirit_electric_vortex_debuff.vpcf", context)
	PrecacheResource("particle", "particles/units/heroes/hero_stormspirit/stormspirit_static_remnant_glow.vpcf", context)
	PrecacheResource("particle", "particles/units/heroes/hero_stormspirit/stormspirit_overload_discharge.vpcf", context)
	PrecacheResource("particle", "particles/units/heroes/hero_leshrac/leshrac_split_earth.vpcf", context)
	PrecacheResource("particle", "particles/units/heroes/hero_leshrac/leshrac_diabolic_edict.vpcf", context)
	PrecacheResource("particle", "particles/units/heroes/hero_leshrac/leshrac_lightning_bolt.vpcf", context)
	PrecacheResource("particle", "particles/units/heroes/hero_leshrac/leshrac_pulse_nova.vpcf", context)
	PrecacheResource("particle", "particles/units/heroes/hero_invoker/invoker_chaos_meteor.vpcf", context)
	PrecacheResource("particle", "particles/units/heroes/hero_invoker/invoker_sun_strike.vpcf", context)
	PrecacheResource("particle", "particles/units/heroes/hero_invoker/invoker_deafening_blast.vpcf", context)
	PrecacheResource("particle", "particles/units/heroes/hero_invoker/invoker_emp.vpcf", context)
	PrecacheResource("particle", "particles/units/heroes/hero_puck/puck_illusory_orb.vpcf", context)
	PrecacheResource("particle", "particles/units/heroes/hero_puck/puck_waning_rift.vpcf", context)
	PrecacheResource("particle", "particles/units/heroes/hero_puck/puck_phase_shift.vpcf", context)
	PrecacheResource("particle", "particles/units/heroes/hero_puck/puck_dreamcoil.vpcf", context)
	PrecacheResource("particle", "particles/units/heroes/hero_lion/lion_spell_impale.vpcf", context)
	PrecacheResource("particle", "particles/units/heroes/hero_lion/lion_spell_impale_hit_spikes.vpcf", context)
	PrecacheResource("particle", "particles/units/heroes/hero_lion/lion_spell_voodoo.vpcf", context)
	PrecacheResource("particle", "particles/units/heroes/hero_lion/lion_spell_mana_drain.vpcf", context)
	PrecacheResource("particle", "particles/units/heroes/hero_lion/lion_spell_finger_of_death.vpcf", context)
	PrecacheResource("particle", "particles/units/heroes/hero_jakiro/jakiro_dual_breath_fire.vpcf", context)
	PrecacheResource("particle", "particles/units/heroes/hero_jakiro/jakiro_ice_path.vpcf", context)
	PrecacheResource("particle", "particles/units/heroes/hero_jakiro/jakiro_liquid_fire_explosion.vpcf", context)
	PrecacheResource("particle", "particles/units/heroes/hero_jakiro/jakiro_macropyre.vpcf", context)
	PrecacheResource("particle", "particles/units/heroes/hero_vengeful/vengeful_magic_missle.vpcf", context)
	PrecacheResource("particle", "particles/units/heroes/hero_vengeful/vengeful_wave_of_terror.vpcf", context)
	PrecacheResource("particle", "particles/units/heroes/hero_vengeful/vengeful_nether_swap.vpcf", context)
	PrecacheResource("particle", "particles/units/heroes/hero_vengeful/vengeful_nether_swap_target.vpcf", context)
	PrecacheResource("particle", "particles/units/heroes/hero_lich/lich_frost_nova.vpcf", context)
	PrecacheResource("particle", "particles/units/heroes/hero_lich/lich_frost_armor.vpcf", context)
	PrecacheResource("particle", "particles/units/heroes/hero_lich/lich_gaze.vpcf", context)
	PrecacheResource("particle", "particles/units/heroes/hero_lich/lich_chain_frost.vpcf", context)
	PrecacheResource("particle", "particles/units/heroes/hero_juggernaut/juggernaut_blade_fury.vpcf", context)
	PrecacheResource("particle", "particles/units/heroes/hero_juggernaut/juggernaut_healing_ward.vpcf", context)
	PrecacheResource("particle", "particles/units/heroes/hero_juggernaut/jugg_crit_blur.vpcf", context)
	PrecacheResource("particle", "particles/units/heroes/hero_juggernaut/juggernaut_omni_slash.vpcf", context)
	PrecacheResource("particle", "particles/units/heroes/hero_drow/drow_frost_arrow.vpcf", context)
	PrecacheResource("particle", "particles/units/heroes/hero_drow/drow_silence_wave.vpcf", context)
	PrecacheResource("particle", "particles/units/heroes/hero_drow/drow_multishot_proj_linear_proj.vpcf", context)
	PrecacheResource("particle", "particles/units/heroes/hero_drow/drow_marksmanship_frost_arrow.vpcf", context)
	PrecacheResource("particle", "particles/units/heroes/hero_drow/drow_precision.vpcf", context)
	PrecacheResource("particle", "particles/units/heroes/hero_lina/lina_spell_dragon_slave.vpcf", context)
	PrecacheResource("particle", "particles/units/heroes/hero_lina/lina_spell_light_strike_array.vpcf", context)
	PrecacheResource("particle", "particles/units/heroes/hero_lina/lina_fiery_soul.vpcf", context)
	PrecacheResource("particle", "particles/units/heroes/hero_jakiro/jakiro_liquid_fire_debuff.vpcf", context)
	PrecacheResource("particle", "particles/units/heroes/hero_lina/lina_spell_laguna_blade.vpcf", context)
	PrecacheResource("particle", "particles/units/heroes/hero_omniknight/omniknight_purification.vpcf", context)
	PrecacheResource("particle", "particles/units/heroes/hero_omniknight/omniknight_repel_buff.vpcf", context)
	PrecacheResource("particle", "particles/units/heroes/hero_omniknight/omniknight_degen_aura.vpcf", context)
	PrecacheResource("particle", "particles/units/heroes/hero_omniknight/omniknight_degen_aura_debuff.vpcf", context)
	PrecacheResource("particle", "particles/units/heroes/hero_omniknight/omniknight_guardian_angel_omni.vpcf", context)
	PrecacheResource("particle", "particles/units/heroes/hero_omniknight/omniknight_guardian_angel_ally.vpcf", context)
	PrecacheResource("particle", "particles/units/heroes/hero_omniknight/omniknight_hammer_of_purity_detonation.vpcf", context)
	PrecacheResource("particle", "particles/rain_fx/coloseum_terrain_motes.vpcf", context)
	PrecacheResource("particle", "particles/units/heroes/hero_axe/axe_beserkers_call_owner.vpcf", context)
	PrecacheResource("particle", "particles/units/heroes/hero_axe/axe_battle_hunger.vpcf", context)
	PrecacheResource("particle", "particles/units/heroes/hero_axe/axe_counterhelix.vpcf", context)
	PrecacheResource("particle", "particles/units/heroes/hero_axe/axe_culling_blade.vpcf", context)
	PrecacheResource("particle", "particles/units/heroes/hero_axe/axe_culling_blade_hit_sparks.vpcf", context)
	PrecacheResource("particle", "particles/units/heroes/hero_centaur/centaur_warstomp.vpcf", context)
	PrecacheResource("particle", "particles/units/heroes/hero_centaur/centaur_double_edge.vpcf", context)
	PrecacheResource("particle", "particles/units/heroes/hero_centaur/centaur_return.vpcf", context)
	PrecacheResource("particle", "particles/units/heroes/hero_centaur/centaur_stampede_cast.vpcf", context)
	PrecacheResource("particle", "particles/units/heroes/hero_centaur/centaur_stampede_haste.vpcf", context)
	PrecacheResource("particle", "particles/units/heroes/hero_sniper/sniper_take_aim_overhead.vpcf", context)
	PrecacheResource("particle", "particles/units/heroes/hero_sniper/sniper_assassinate_impact_sparks.vpcf", context)
	PrecacheResource("particle", "particles/units/heroes/hero_crystalmaiden/maiden_crystal_nova.vpcf", context)
	PrecacheResource("particle", "particles/units/heroes/hero_crystalmaiden/maiden_frostbite_buff.vpcf", context)
	PrecacheResource("particle", "particles/units/heroes/hero_crystalmaiden/maiden_freezing_field_caster.vpcf", context)
	PrecacheResource("particle", "particles/units/heroes/hero_crystalmaiden/maiden_freezing_field_snow.vpcf", context)
	PrecacheResource("particle", "particles/units/heroes/hero_crystalmaiden/maiden_freezing_field_explosion.vpcf", context)
	PrecacheResource("particle", "particles/units/heroes/hero_dazzle/dazzle_poison_touch.vpcf", context)
	PrecacheResource("particle", "particles/units/heroes/hero_dazzle/dazzle_shallow_grave.vpcf", context)
	PrecacheResource("particle", "particles/units/heroes/hero_dazzle/dazzle_shadow_wave.vpcf", context)
	PrecacheResource("particle", "particles/units/heroes/hero_dazzle/dazzle_armor_friend.vpcf", context)
	PrecacheResource("particle", "particles/units/heroes/hero_dazzle/dazzle_armor_enemy.vpcf", context)
	PrecacheResource("particle", "particles/units/heroes/hero_legion_commander/legion_commander_odds.vpcf", context)
	PrecacheResource("particle", "particles/units/heroes/hero_legion_commander/legion_commander_press.vpcf", context)
	PrecacheResource("particle", "particles/units/heroes/hero_legion_commander/legion_commander_courage_hit.vpcf", context)
	PrecacheResource("particle", "particles/units/heroes/hero_legion_commander/legion_commander_duel_victory.vpcf", context)
	PrecacheResource("particle", "particles/units/heroes/hero_legion_commander/legion_commander_duel_buff.vpcf", context)
	PrecacheResource("particle", "particles/units/heroes/hero_legion_commander/legion_duel_ring.vpcf", context)
	PrecacheResource("particle", "particles/units/heroes/hero_sniper/sniper_shrapnel.vpcf", context)
	PrecacheResource("particle", "particles/units/heroes/hero_sniper/sniper_assassinate.vpcf", context)
	PrecacheResource("particle", "particles/units/heroes/hero_crystalmaiden/maiden_crystal_nova.vpcf", context)
	PrecacheResource("particle", "particles/units/heroes/hero_crystalmaiden/maiden_frostbite_buff.vpcf", context)
	PrecacheResource("particle", "particles/units/heroes/hero_crystalmaiden/maiden_freezing_field_snow.vpcf", context)
	PrecacheResource("particle", "particles/units/heroes/hero_dazzle/dazzle_poison_touch.vpcf", context)
	PrecacheResource("particle", "particles/units/heroes/hero_dazzle/dazzle_shallow_grave.vpcf", context)
	PrecacheResource("particle", "particles/units/heroes/hero_dazzle/dazzle_shadow_wave.vpcf", context)
	PrecacheResource("particle", "particles/units/heroes/hero_sven/sven_spell_gods_strength.vpcf", context)
	PrecacheResource("particle", "particles/units/heroes/hero_sven/sven_gods_strength_hero_effect.vpcf", context)
	PrecacheResource("particle", "particles/units/heroes/hero_centaur/centaur_warstomp.vpcf", context)
	PrecacheResource("particle", "particles/units/heroes/hero_centaur/centaur_double_edge.vpcf", context)
	PrecacheResource("particle", "particles/units/heroes/hero_centaur/centaur_return.vpcf", context)
	PrecacheResource("particle", "particles/units/heroes/hero_centaur/centaur_stampede.vpcf", context)
	PrecacheResource("particle", "particles/units/heroes/hero_skeletonking/skeletonking_hellfireblast.vpcf", context)
	PrecacheResource("particle", "particles/units/heroes/hero_skeletonking/skeletonking_hellfireblast_explosion.vpcf", context)
	PrecacheResource("particle", "particles/units/heroes/hero_skeletonking/skeletonking_hellfireblast_debuff.vpcf", context)
	PrecacheResource("particle", "particles/units/heroes/hero_skeletonking/skeletonking_mortalstrike.vpcf", context)
	PrecacheResource("particle", "particles/units/heroes/hero_skeletonking/skeletonking_reincarnation.vpcf", context)
	PrecacheResource("particle", "particles/units/heroes/hero_skeletonking/wraith_king_vampiric_aura_lifesteal.vpcf", context)
	PrecacheResource("particle", "particles/units/heroes/hero_phantom_assassin/phantom_assassin_stifling_dagger.vpcf", context)
	PrecacheResource("particle", "particles/units/heroes/hero_phantom_assassin/phantom_assassin_stifling_dagger_explosion.vpcf", context)
	PrecacheResource("particle", "particles/units/heroes/hero_phantom_assassin/phantom_assassin_crit_impact.vpcf", context)
	PrecacheResource("particle", "particles/units/heroes/hero_phantom_assassin/phantom_assassin_phantom_strike_start.vpcf", context)
	PrecacheResource("particle", "particles/units/heroes/hero_phantom_assassin/phantom_assassin_phantom_strike_end.vpcf", context)
	PrecacheResource("particle", "particles/units/heroes/hero_zuus/zuus_arc_lightning.vpcf", context)
	PrecacheResource("particle", "particles/units/heroes/hero_zuus/zuus_lightning_bolt.vpcf", context)
	PrecacheResource("particle", "particles/units/heroes/hero_zuus/zuus_thundergods_wrath.vpcf", context)
	PrecacheResource("particle", "particles/units/heroes/hero_zuus/zuus_shard_jump_launch_ring.vpcf", context)
	PrecacheResource("particle", "particles/units/heroes/hero_zuus/zuus_shard_jump_landing_ring.vpcf", context)
	PrecacheResource("particle", "particles/units/heroes/hero_witchdoctor/witchdoctor_cask.vpcf", context)
	PrecacheResource("particle", "particles/units/heroes/hero_witchdoctor/witchdoctor_voodoo_restoration_aura.vpcf", context)
	PrecacheResource("particle", "particles/units/heroes/hero_witchdoctor/witchdoctor_maledict.vpcf", context)
	PrecacheResource("particle", "particles/units/heroes/hero_witchdoctor/witchdoctor_ward_attack.vpcf", context)
	PrecacheResource("particle", "particles/units/heroes/hero_witchdoctor/witchdoctor_ward_summon.vpcf", context)
	PrecacheUnitByNameSync("npc_dota_witch_doctor_death_ward", context)
	PrecacheResource("particle", "particles/units/heroes/hero_bristleback/bristleback_quill_spray.vpcf", context)
	PrecacheResource("particle", "particles/units/heroes/hero_bristleback/bristleback_viscous_nasal_goo.vpcf", context)
	PrecacheResource("particle", "particles/units/heroes/hero_bristleback/bristleback_warpath.vpcf", context)
	PrecacheResource("particle", "particles/units/heroes/hero_slark/slark_dark_pact_pulses.vpcf", context)
	PrecacheResource("particle", "particles/units/heroes/hero_slark/slark_shadow_dance.vpcf", context)
	PrecacheResource("particle", "particles/units/heroes/hero_slark/slark_pounce_start.vpcf", context)
	PrecacheResource("particle", "particles/units/heroes/hero_slark/slark_pounce_trail.vpcf", context)
	PrecacheResource("particle", "particles/units/heroes/hero_slark/slark_pounce_splash.vpcf", context)
	PrecacheResource("particle", "particles/units/heroes/hero_slark/slark_pounce_leash.vpcf", context)
	PrecacheResource("particle", "particles/units/heroes/hero_slark/slark_essence_shift_hit_glow.vpcf", context)
	PrecacheResource("particle", "particles/units/heroes/hero_slark/slark_shard_fish_bait_impact_splash.vpcf", context)
	PrecacheResource("particle", "particles/units/heroes/hero_luna/luna_lucent_beam.vpcf", context)
	PrecacheResource("particle", "particles/units/heroes/hero_luna/luna_eclipse.vpcf", context)
	PrecacheResource("particle", "particles/units/heroes/hero_nevermore/nevermore_shadowraze.vpcf", context)
	PrecacheResource("particle", "particles/units/heroes/hero_nevermore/nevermore_requiemofsouls.vpcf", context)
	PrecacheResource("particle", "particles/units/heroes/hero_shadowshaman/shadowshaman_ether_shock.vpcf", context)
	PrecacheResource("particle", "particles/units/heroes/hero_shadowshaman/shadowshaman_shackle.vpcf", context)
	PrecacheUnitByNameSync("npc_dota_courier", context)
	PrecacheUnitByNameSync("npc_dota_flying_courier", context)
	PrecacheUnitByNameSync("enfos_spellbringer_war_standard", context)
	PrecacheUnitByNameSync("enfos_spellbringer_thorn_idol", context)
	PrecacheUnitByNameSync("enfos_spellbringer_void_stalker", context)
	PrecacheUnitByNameSync("enfos_spellbringer_reinforcement", context)
end

function Activate()
	print("[ENFOS_BOOT] Activate begin")
	GameRules.EnfosSametC = EnfosSametC()
	GameRules.EnfosSametC:InitGameMode()
	print("[ENFOS_BOOT] game mode initialized")
	WaveManager:Init()
	print("[ENFOS_BOOT] wave manager initialized")
	-- Register setup input and publish the first setup snapshot before optional
	-- game systems initialize. A failure in those systems must not leave the
	-- player stranded with the Panorama fallback screen and no working controls.
	local setupManager = require("setup/enfos_setup_manager")
	setupManager:Init(WaveManager)
	print("[ENFOS_BOOT] setup manager initialized")
	require("map/portals"):Init()
	print("[ENFOS_BOOT] portals initialized")
	require("spellbringer/spellbringer_service"):Init(WaveManager)
	print("[ENFOS_BOOT] spellbringer initialized")
	local economyManager = require("economy/economy_manager")
	economyManager:Init(WaveManager)
	require("economy/ascended_shop"):Init(economyManager)
	print("[ENFOS_BOOT] economy initialized")
	local boonManager = require("boons/boon_manager")
	boonManager:Init(WaveManager, economyManager, require("spellbringer/spellbringer_service"))
	print("[ENFOS_BOOT] boon manager initialized")
	local aghanimManager = require("heroes/aghanim_manager")
	aghanimManager:Init()
	print("[ENFOS_BOOT] Activate complete")
end
