import fs from 'node:fs';
import {parseKV} from './lib/kv.mjs';
const config=JSON.parse(fs.readFileSync('config/hero_evolutions.json','utf8'));
if(JSON.stringify(config.milestones)!=='[4,7,10,13,16,19]' || config.pairs.length!==6 || config.pairs.some(p=>p.length!==2 || p[0]===p[1] || p.some(i=>!Number.isInteger(i)||i<0||i>5)))throw Error('Invalid tree tiers');
const heroes=parseKV(fs.readFileSync('game/scripts/npc/npc_heroes_custom.txt','utf8')).DOTAHeroes;
const abilities=parseKV(fs.readFileSync('game/scripts/npc/npc_abilities_custom.txt','utf8')).DOTAAbilities;
const audit=JSON.parse(fs.readFileSync('docs/audit/HERO_ABILITY_CONTRACTS.json','utf8'));
const audited=new Map(audit.heroes.flatMap(h=>h.abilities).map(a=>[a.id,a]));
const lines=['-- Generated by tools/hero_evolutions.mjs from reviewed skill-specific profiles.','return {'];
let count=0;
for(const [short,profile]of Object.entries(config.profiles)){
 const id='npc_dota_hero_'+short,hero=heroes[id];if(!hero)throw Error('Unknown hero '+id);
 const paths=profile.split(' ').map((entry,index)=>{
  const m=entry.match(/^(\d)\.(\w+):([+*])([\d.]+)$/);if(!m)throw Error(entry);
  const [,slot,key,mode,n]=m,ability=hero['Ability'+slot],kv=abilities[ability],amount=Number(n);
  if(key==='cooldown'){
   if(!String(kv.AbilityCooldown||'').split(/\s+/).some(v=>Number(v)>0)||kv.AbilityBehavior.includes('TOGGLE'))throw Error('No cooldown: '+ability);
  }else{
   if(!(key in audited.get(ability).specials)||audited.get(ability).unreferencedSpecials.includes(key))throw Error('Unimplemented field: '+ability+'.'+key);
  }
  if(amount<=0 || (mode==='*'&&amount>15))throw Error('Out of budget: '+entry);
  return {ability,key,mode,amount,index};
 });
 if(paths.length!==6)throw Error('Expected six distinct focus paths: '+id);
 if(new Set(paths.map(p=>p.ability+'.'+p.key)).size!==6)throw Error('Duplicate focus: '+id);
 lines.push(` ["${id}"]={`);
 config.milestones.forEach((level,tier)=>{
  lines.push(`  [${level}]={`);
  for(const [side,index]of config.pairs[tier].entries()){
   const p=paths[index],choiceId=`evo_${short}_${level}_${side+1}`;
   lines.push(`   {id="${choiceId}",hero="${id}",tier=${tier},side=${side+1},ability="${p.ability}",icon="${p.ability}",special="${p.key}",mode="${p.mode}",amount=${p.amount}},`);count++;
  }
  lines.push('  },');
 });lines.push(' },');
}
if(Object.keys(config.profiles).length!==40||count!==480)throw Error('Incomplete roster');
lines.push('}');const out=lines.join('\n')+'\n',file='game/scripts/vscripts/evolution/hero_choices.lua';
if(process.argv.includes('--check')){if(fs.readFileSync(file,'utf8')!==out)throw Error('Stale hero choices');}else fs.writeFileSync(file,out);
console.log('PASS 40 hero trees / 480 choices; every target has a live KV consumer or native cooldown.');
