import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { parseKV } from './lib/kv.mjs';

export const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');

// Turkish is the source of truth.  Other languages auto-mirror Turkish
// tokens until real translations are provided.
export const SOURCE_LANG = 'turkish';
export const languages = ['english', 'turkish', 'russian', 'schinese'];
const langDisplayName = { english: 'English', turkish: 'Turkish', russian: 'Russian', schinese: 'SChinese' };

export function generateLocalization(check = false) {
  const abilities = parseKV(fs.readFileSync(path.join(root, 'game/scripts/npc/npc_abilities_custom.txt'), 'utf8')).DOTAAbilities;
  const items = parseKV(fs.readFileSync(path.join(root, 'game/scripts/npc/npc_items_custom.txt'), 'utf8')).DOTAItems;

  // Load Turkish source first
  const sourceData = JSON.parse(fs.readFileSync(path.join(root, `localization/${SOURCE_LANG}.json`), 'utf8'));
  const sourceKeys = Object.keys(sourceData.Tokens).sort();

  const escape = value => value.replaceAll('"', '\\"');

  const resolveSpecials = (key, rawValue) => {
    const id = key.match(/^DOTA_Tooltip_[Aa]bility_(.+)_(?:Description|SummaryDescription)$/)?.[1];
    const definition = abilities[id] ?? items[id];
    const specials = Object.assign({}, ...Object.values(definition?.AbilitySpecial ?? {}));
    return rawValue.replace(/\{\{(\w+)(?:\|(\w+))?\}\}/g, (_, name, format) => {
      if (specials[name] === undefined) throw new Error(`${key}: unknown special ${name}`);
      const values = specials[name].split(/\s+/);
      if (format === 'abs') return values.map(v => Math.abs(Number(v))).join(' / ');
      if (format === 'percent') return values.map(v => `${Math.abs(Number(v))}%`).join(' / ');
      if (format === 'plus') return values.join(' / +');
      if (format) throw new Error(`Unknown format: ${format}`);
      return values.join(' / ');
    });
  };

  for (const lang of languages) {
    let data;
    if (lang === SOURCE_LANG) {
      data = sourceData;
    } else {
      // Mirror: use existing lang file but fill missing tokens from Turkish
      const langFile = path.join(root, `localization/${lang}.json`);
      data = JSON.parse(fs.readFileSync(langFile, 'utf8'));
      for (const key of sourceKeys) {
        if (!(key in data.Tokens)) {
          data.Tokens[key] = sourceData.Tokens[key]; // Turkish placeholder
        }
      }
    }

    const keys = Object.keys(data.Tokens).sort();
    const lines = keys.map(key => {
      const value = resolveSpecials(key, data.Tokens[key]);
      if (!value || value.includes('{{')) throw new Error(`${lang}/${key}: empty or unresolved text`);
      return `\t\t"${key}" "${escape(value)}"`;
    });
    const displayLang = langDisplayName[lang] ?? lang;
    const output = `// Generated by tools/localization.mjs; edit localization/${SOURCE_LANG}.json.\n"lang"\n{\n\t"Language" "${displayLang}"\n\t"Tokens"\n\t{\n${lines.join('\n')}\n\t}\n}\n`;
    for (const dir of ['game/resource', 'game/panorama/localization']) {
      const target = path.join(root, dir, `addon_${lang}.txt`);
      if (check) {
        if (fs.readFileSync(target, 'utf8') !== output) throw new Error(`${target}: generated localization is stale`);
      } else fs.writeFileSync(target, output);
    }
  }
}
if (process.argv[1] && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  generateLocalization(process.argv.includes('--check'));
  console.log(`Localization: Turkish source → all ${languages.length} languages synchronized.`);
}
