import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { parseKV } from './lib/kv.mjs';

export const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
export const languages = ['english', 'turkish', 'russian', 'schinese'];
export function generateLocalization(check = false) {
  const abilities = parseKV(fs.readFileSync(path.join(root, 'game/scripts/npc/npc_abilities_custom.txt'), 'utf8')).DOTAAbilities;
  const items = parseKV(fs.readFileSync(path.join(root, 'game/scripts/npc/npc_items_custom.txt'), 'utf8')).DOTAItems;
  let baseline;
  for (const lang of languages) {
    const data = JSON.parse(fs.readFileSync(path.join(root, `localization/${lang}.json`), 'utf8'));
    const keys = Object.keys(data.Tokens).sort();
    baseline ??= keys;
    if (JSON.stringify(keys) !== JSON.stringify(baseline)) throw new Error(`${lang}: localization key coverage differs`);
    const escape = value => value.replaceAll('"', '\\"');
    const lines = keys.map(key => {
      const id = key.match(/^DOTA_Tooltip_[Aa]bility_(.+)_(?:Description|SummaryDescription)$/)?.[1];
      const definition = abilities[id] ?? items[id];
      const specials = Object.assign({}, ...Object.values(definition?.AbilitySpecial ?? {}));
      const value = data.Tokens[key].replace(/\{\{(\w+)(?:\|(\w+))?\}\}/g, (_, name, format) => {
        if (specials[name] === undefined) throw new Error(`${lang}/${key}: unknown special ${name}`);
        const values = specials[name].split(/\s+/);
        if (format === 'abs') return values.map(v => Math.abs(Number(v))).join(' / ');
        if (format === 'percent') return values.map(v => `${Math.abs(Number(v))}%`).join(' / ');
        if (format === 'plus') return values.join(' / +');
        if (format) throw new Error(`Unknown format: ${format}`);
        return values.join(' / ');
      });
      if (!value || value.includes('{{')) throw new Error(`${lang}/${key}: empty or unresolved text`);
      return `\t\t"${key}" "${escape(value)}"`;
    });
    const output = `// Generated by tools/localization.mjs; edit localization/${lang}.json.\n"lang"\n{\n\t"Language" "${data.Language}"\n\t"Tokens"\n\t{\n${lines.join('\n')}\n\t}\n}\n`;
    for (const dir of ['game/resource', 'game/panorama/localization']) {
      const target = path.join(root, dir, `addon_${lang}.txt`);
      if (check) {
        if (fs.readFileSync(target, 'utf8') !== output) throw new Error(`${target}: generated localization is stale`);
      } else fs.writeFileSync(target, output);
    }
  }
}
if (process.argv[1] && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  generateLocalization(process.argv.includes('--check'));
  console.log('Localization: four languages synchronized with gameplay values.');
}
