import fs from 'node:fs';
import path from 'node:path';
import { pathToFileURL } from 'node:url';

const server = 'C:/Users/samet/.gemini/antigravity/mcp/dota2_workshop_mcp';
const dota = 'C:/Program Files (x86)/Steam/steamapps/common/dota 2 beta';
const { Vpk } = await import(pathToFileURL(path.join(server, 'dist/dota/vpk.js')));
const valve = await Vpk.open(path.join(dota, 'game/dota/pak01_dir.vpk'));

const particles = [
  'particles/units/heroes/hero_axe/axe_beserkers_call_owner.vpcf',
  'particles/units/heroes/hero_axe/axe_battle_hunger.vpcf',
  'particles/units/heroes/hero_axe/axe_counterhelix.vpcf',
  'particles/units/heroes/hero_axe/axe_culling_blade.vpcf',
  'particles/units/heroes/hero_axe/axe_culling_blade_hit_sparks.vpcf',
  'particles/units/heroes/hero_centaur/centaur_warstomp.vpcf',
  'particles/units/heroes/hero_centaur/centaur_double_edge.vpcf',
  'particles/units/heroes/hero_centaur/centaur_return.vpcf',
  'particles/units/heroes/hero_centaur/centaur_stampede_cast.vpcf',
  'particles/units/heroes/hero_centaur/centaur_stampede_haste.vpcf',
  'particles/units/heroes/hero_sniper/sniper_shrapnel.vpcf',
  'particles/units/heroes/hero_sniper/sniper_assassinate.vpcf',
  'particles/units/heroes/hero_sniper/sniper_assassinate_impact_sparks.vpcf',
  'particles/units/heroes/hero_sniper/sniper_take_aim_overhead.vpcf',
  'particles/units/heroes/hero_crystalmaiden/maiden_crystal_nova.vpcf',
  'particles/units/heroes/hero_crystalmaiden/maiden_frostbite_buff.vpcf',
  'particles/units/heroes/hero_crystalmaiden/maiden_freezing_field_caster.vpcf',
  'particles/units/heroes/hero_crystalmaiden/maiden_freezing_field_snow.vpcf',
  'particles/units/heroes/hero_dazzle/dazzle_poison_touch.vpcf',
  'particles/units/heroes/hero_dazzle/dazzle_shallow_grave.vpcf',
  'particles/units/heroes/hero_dazzle/dazzle_shadow_wave.vpcf',
  'particles/units/heroes/hero_dazzle/dazzle_armor_friend.vpcf',
  'particles/units/heroes/hero_dazzle/dazzle_armor_enemy.vpcf',
  'particles/units/heroes/hero_bristleback/bristleback_viscous_nasal_goo.vpcf',
  'particles/units/heroes/hero_bristleback/bristleback_warpath.vpcf',
  'particles/units/heroes/hero_bristleback/bristleback_quill_spray.vpcf',
  'particles/units/heroes/hero_juggernaut/juggernaut_blade_fury.vpcf',
  'particles/units/heroes/hero_juggernaut/juggernaut_healing_ward.vpcf',
  'particles/units/heroes/hero_juggernaut/jugg_crit_blur.vpcf',
  'particles/units/heroes/hero_juggernaut/juggernaut_omni_slash.vpcf',
  'particles/units/heroes/hero_drow/drow_frost_arrow.vpcf',
  'particles/units/heroes/hero_drow/drow_silence_wave.vpcf',
  'particles/units/heroes/hero_drow/drow_multishot_proj_linear_proj.vpcf',
  'particles/units/heroes/hero_drow/drow_marksmanship_frost_arrow.vpcf',
  'particles/units/heroes/hero_lina/lina_spell_dragon_slave.vpcf',
  'particles/units/heroes/hero_lina/lina_spell_light_strike_array.vpcf',
  'particles/units/heroes/hero_lina/lina_fiery_soul.vpcf',
  'particles/units/heroes/hero_lina/lina_spell_laguna_blade.vpcf',
  'particles/units/heroes/hero_omniknight/omniknight_purification.vpcf',
  'particles/units/heroes/hero_omniknight/omniknight_repel_buff.vpcf',
  'particles/units/heroes/hero_omniknight/omniknight_degen_aura.vpcf',
  'particles/units/heroes/hero_omniknight/omniknight_degen_aura_debuff.vpcf',
  'particles/units/heroes/hero_omniknight/omniknight_guardian_angel_omni.vpcf',
  'particles/units/heroes/hero_omniknight/omniknight_hammer_of_purity_detonation.vpcf',
  'particles/units/heroes/hero_tidehunter/tidehunter_gush.vpcf',
  'particles/units/heroes/hero_tidehunter/tidehunter_anchor_hero.vpcf',
  'particles/units/heroes/hero_tidehunter/tidehunter_spell_ravage.vpcf',
  'particles/units/heroes/hero_skeletonking/skeletonking_hellfireblast.vpcf',
  'particles/units/heroes/hero_skeletonking/skeletonking_hellfireblast_explosion.vpcf',
  'particles/units/heroes/hero_skeletonking/skeletonking_hellfireblast_debuff.vpcf',
  'particles/units/heroes/hero_skeletonking/skeletonking_mortalstrike.vpcf',
  'particles/units/heroes/hero_skeletonking/skeletonking_reincarnation.vpcf',
  'particles/units/heroes/hero_skeletonking/wraith_king_vampiric_aura_lifesteal.vpcf',
  'particles/units/heroes/hero_phantom_assassin/phantom_assassin_stifling_dagger.vpcf',
  'particles/units/heroes/hero_phantom_assassin/phantom_assassin_stifling_dagger_explosion.vpcf',
  'particles/units/heroes/hero_phantom_assassin/phantom_assassin_crit_impact.vpcf',
  'particles/units/heroes/hero_phantom_assassin/phantom_assassin_phantom_strike_start.vpcf',
  'particles/units/heroes/hero_phantom_assassin/phantom_assassin_phantom_strike_end.vpcf',
  'particles/units/heroes/hero_zuus/zuus_arc_lightning.vpcf',
  'particles/units/heroes/hero_zuus/zuus_lightning_bolt.vpcf',
  'particles/units/heroes/hero_zuus/zuus_thundergods_wrath.vpcf',
  'particles/units/heroes/hero_zuus/zuus_shard_jump_launch_ring.vpcf',
  'particles/units/heroes/hero_zuus/zuus_shard_jump_landing_ring.vpcf',
  'particles/units/heroes/hero_witchdoctor/witchdoctor_cask.vpcf',
  'particles/units/heroes/hero_witchdoctor/witchdoctor_voodoo_restoration_aura.vpcf',
  'particles/units/heroes/hero_witchdoctor/witchdoctor_maledict.vpcf',
  'particles/units/heroes/hero_witchdoctor/witchdoctor_ward_attack.vpcf',
  'particles/units/heroes/hero_witchdoctor/witchdoctor_ward_summon.vpcf',
  'particles/units/heroes/hero_dragon_knight/dragon_knight_breathe_fire.vpcf',
  'particles/units/heroes/hero_dragon_knight/dragon_knight_breathe_fire_explosion.vpcf',
  'particles/units/heroes/hero_dragon_knight/dragon_knight_dragon_tail_impact.vpcf',
  'particles/units/heroes/hero_dragon_knight/dragon_knight_transform_red.vpcf',
  'particles/units/heroes/hero_dragon_knight/dragon_knight_elder_dragon_fire.vpcf',
  'particles/units/heroes/hero_dragon_knight/dragon_knight_elder_dragon_fire_explosion.vpcf',
  'particles/units/heroes/hero_pudge/pudge_meathook.vpcf',
  'particles/units/heroes/hero_pudge/pudge_meathook_impact.vpcf',
  'particles/units/heroes/hero_pudge/pudge_rot.vpcf',
  'particles/units/heroes/hero_pudge/pudge_dismember.vpcf',
  'particles/units/heroes/hero_slark/slark_dark_pact_pulses.vpcf',
  'particles/units/heroes/hero_slark/slark_pounce_start.vpcf',
  'particles/units/heroes/hero_slark/slark_pounce_trail.vpcf',
  'particles/units/heroes/hero_slark/slark_pounce_splash.vpcf',
  'particles/units/heroes/hero_slark/slark_pounce_leash.vpcf',
  'particles/units/heroes/hero_slark/slark_essence_shift_hit_glow.vpcf',
  'particles/units/heroes/hero_slark/slark_shadow_dance.vpcf',
  'particles/units/heroes/hero_slark/slark_shard_fish_bait_impact_splash.vpcf',
  'particles/units/heroes/hero_ursa/ursa_earthshock.vpcf',
  'particles/units/heroes/hero_ursa/ursa_overpower_buff.vpcf',
  'particles/units/heroes/hero_ursa/ursa_fury_swipes.vpcf',
  'particles/units/heroes/hero_ursa/ursa_fury_swipes_debuff.vpcf',
  'particles/units/heroes/hero_ursa/ursa_enrage_buff.vpcf',
  'particles/units/heroes/hero_monkey_king/monkey_king_strike.vpcf',
  'particles/units/heroes/hero_monkey_king/mk_strike_path_pulse_hit.vpcf',
  'particles/units/heroes/hero_monkey_king/monkey_king_spring.vpcf',
  'particles/units/heroes/hero_monkey_king/monkey_king_spring_cast.vpcf',
  'particles/units/heroes/hero_monkey_king/monkey_king_furarmy_aoe.vpcf',
  'particles/units/heroes/hero_monkey_king/monkey_king_fur_army_attack.vpcf',
  'particles/units/heroes/hero_monkey_king/monkey_king_furarmy_singlemonkey_attack_swipe.vpcf',
  'particles/units/heroes/hero_troll_warlord/troll_warlord_whirling_axe_melee.vpcf',
  'particles/units/heroes/hero_troll_warlord/troll_warlord_battletrance_buff.vpcf',
  'particles/units/heroes/hero_troll_warlord/troll_warlord_battletrance_cast.vpcf',
  'particles/units/heroes/hero_troll_warlord/troll_warlord_rampage_attack_speed_buff.vpcf',
  'particles/units/heroes/hero_troll_warlord/troll_warlord_rampage_resistance_buff.vpcf',
  'particles/generic_gameplay/generic_stunned.vpcf',
  'particles/units/heroes/hero_chaos_knight/chaos_knight_chaos_bolt.vpcf',
  'particles/units/heroes/hero_chaos_knight/chaos_knight_reality_rift.vpcf',
  'particles/units/heroes/hero_chaos_knight/chaos_knight_reality_rift_buff.vpcf',
  'particles/units/heroes/hero_chaos_knight/chaos_knight_phantasm.vpcf',
  'particles/units/heroes/hero_chaos_knight/chaos_knight_weapon_blur_critical.vpcf',
  'particles/units/heroes/hero_antimage/antimage_manabreak_enemy_debuff.vpcf',
  'particles/units/heroes/hero_antimage/antimage_blink_start.vpcf',
  'particles/units/heroes/hero_antimage/antimage_blink_end.vpcf',
  'particles/units/heroes/hero_antimage/antimage_spellshield.vpcf',
  'particles/units/heroes/hero_antimage/antimage_manavoid.vpcf',
  'particles/units/heroes/hero_faceless_void/faceless_void_time_walk.vpcf',
  'particles/units/heroes/hero_faceless_void/faceless_void_timedialate.vpcf',
  'particles/units/heroes/hero_faceless_void/faceless_void_dialatedebuf.vpcf',
  'particles/units/heroes/hero_faceless_void/faceless_void_time_lock_bash.vpcf',
  'particles/units/heroes/hero_faceless_void/faceless_void_chronosphere.vpcf',
  'particles/units/heroes/hero_faceless_void/faceless_void_backtrack.vpcf',
  'particles/units/heroes/hero_medusa/medusa_base_attack.vpcf',
  'particles/units/heroes/hero_medusa/medusa_base_attack_impact.vpcf',
  'particles/units/heroes/hero_medusa/medusa_mystic_snake_projectile.vpcf',
  'particles/units/heroes/hero_medusa/medusa_mystic_snake_impact.vpcf',
  'particles/units/heroes/hero_medusa/medusa_stone_gaze_active.vpcf',
  'particles/units/heroes/hero_medusa/medusa_stone_gaze_debuff.vpcf',
  'particles/units/heroes/hero_stormspirit/stormspirit_static_remnant.vpcf',
  'particles/units/heroes/hero_stormspirit/stormspirit_electric_vortex.vpcf',
  'particles/units/heroes/hero_stormspirit/stormspirit_electric_vortex_debuff.vpcf',
  'particles/units/heroes/hero_stormspirit/stormspirit_static_remnant_glow.vpcf',
  'particles/units/heroes/hero_stormspirit/stormspirit_overload_discharge.vpcf',
  'particles/units/heroes/hero_stormspirit/stormspirit_ball_lightning.vpcf',
  'particles/units/heroes/hero_leshrac/leshrac_split_earth.vpcf',
  'particles/units/heroes/hero_leshrac/leshrac_diabolic_edict.vpcf',
  'particles/units/heroes/hero_leshrac/leshrac_lightning_bolt.vpcf',
  'particles/units/heroes/hero_leshrac/leshrac_pulse_nova.vpcf',
  'particles/units/heroes/hero_invoker/invoker_chaos_meteor.vpcf',
  'particles/units/heroes/hero_invoker/invoker_sun_strike.vpcf',
  'particles/units/heroes/hero_invoker/invoker_deafening_blast.vpcf',
  'particles/units/heroes/hero_invoker/invoker_emp.vpcf',
  'particles/units/heroes/hero_puck/puck_illusory_orb.vpcf',
  'particles/units/heroes/hero_puck/puck_waning_rift.vpcf',
  'particles/units/heroes/hero_puck/puck_phase_shift.vpcf',
  'particles/units/heroes/hero_puck/puck_dreamcoil.vpcf',
  'particles/units/heroes/hero_lion/lion_spell_impale_hit_spikes.vpcf',
  'particles/units/heroes/hero_lion/lion_spell_voodoo.vpcf',
  'particles/units/heroes/hero_lion/lion_spell_mana_drain.vpcf',
  'particles/units/heroes/hero_lion/lion_spell_finger_of_death.vpcf',
  'particles/units/heroes/hero_jakiro/jakiro_dual_breath_fire.vpcf',
  'particles/units/heroes/hero_jakiro/jakiro_ice_path.vpcf',
  'particles/units/heroes/hero_jakiro/jakiro_liquid_fire_explosion.vpcf',
  'particles/units/heroes/hero_jakiro/jakiro_macropyre.vpcf',
  'particles/units/heroes/hero_vengeful/vengeful_magic_missle.vpcf',
  'particles/units/heroes/hero_vengeful/vengeful_wave_of_terror.vpcf',
  'particles/units/heroes/hero_vengeful/vengeful_nether_swap.vpcf',
  'particles/units/heroes/hero_vengeful/vengeful_nether_swap_target.vpcf',
  'particles/units/heroes/hero_lich/lich_frost_nova.vpcf',
  'particles/units/heroes/hero_lich/lich_frost_armor.vpcf',
  'particles/units/heroes/hero_lich/lich_gaze.vpcf',
  'particles/units/heroes/hero_lich/lich_chain_frost.vpcf',
  'particles/units/heroes/hero_terrorblade/terrorblade_reflection_slow.vpcf',
  'particles/units/heroes/hero_terrorblade/terrorblade_mirror_image.vpcf',
  'particles/units/heroes/hero_terrorblade/terrorblade_metamorphosis.vpcf',
  'particles/units/heroes/hero_terrorblade/terrorblade_metamorphosis_base_attack.vpcf',
  'particles/units/heroes/hero_terrorblade/terrorblade_sunder.vpcf'
];

// Keep the hand-curated native reference list, and also verify every literal
// particle path used by hero Lua or registered for cold-start precache.
const sourceFiles = [
  'game/scripts/vscripts/abilities/pve_kits.lua',
  'game/scripts/vscripts/addon_game_mode.lua'
];
const discovered = new Set();
for (const file of sourceFiles) {
  const source = fs.readFileSync(file, 'utf8');
  for (const match of source.matchAll(/["']([^"']+\.vpcf)["']/gi)) {
    discovered.add(match[1]);
  }
}
const allParticles = [...new Set([...particles, ...discovered])].sort();
console.log(`Checking ${allParticles.length} unique particle paths (${discovered.size} literal Lua/precache references).`);

let allOk = true;
for (const p of allParticles) {
  const c = p + '_c';
  const exists = valve.entries.has(c);
  console.log(p, exists ? 'OK' : 'MISSING');
  if (!exists) allOk = false;
}
if (!allOk) process.exit(1);
console.log('All particles verified in Valve VPK.');
